"""z

Revision ID: 9093cf55e941
Revises: 9205b92827a8
Create Date: 2024-11-13 10:35:46.012550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9093cf55e941'
down_revision: Union[str, None] = '9205b92827a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participation', sa.Column('is_winner', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_participation', 'is_winner')
    # ### end Alembic commands ###
