"""z

Revision ID: ab48673a1815
Revises: f54b1a0f4962
Create Date: 2024-11-13 19:35:14.897171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab48673a1815'
down_revision: Union[str, None] = 'f54b1a0f4962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_mandatory_task', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_mandatory_task')
    # ### end Alembic commands ###
